export const attributeSchema = [
    {
        layer: ['Site index'],
    name: 'Site index (Productivity)',
    attributes: [
      {
        no: 1,
        color: '#d93806',
        idName: -2,
        value: '<= Ic',
      },
      {
        no: 2,
        color: '#fe992c',
        idName: -1,
        value: 'Ic-Ib',
        },
      {
        no: 3,
        color: '#d3e935',
        idNname: 0,
        value: 'Ib-Ia',
        },
      {
        no: 4,
        color: '#64fd6a',
        idName: 1,
        value: 'Ia-I',
        },
      {
        no: 5,
        color: '#1ad1d5',
        idName: 2,
        value: 'I-II',
        },
      {
        no: 6,
        color: '#4777f0',
        idName: 3,
        value: 'II-III',
        },
      {
        no: 7,
        color: '#30123b',
        idName: 4,
        value: '> III',
        },
    ],
    },
    {
        layer: ['Average tree diameter (DBH) as of 2020, cm', 'Average tree diameter (DBH) as of 2050, cm'],
    name: 'Average tree diameter (DBH), cm',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 5,
        value: '<=5',
      },
      {
        no: 2,
        color: '#4686fb',
        idName: 10,
        value: '5-10',
        },
      {
        no: 3,
        color: '#1ae5b6',
        idNname: 20,
        value: '10-20',
        },
      {
        no: 4,
        color: '#a4fc3c',
        idName: 30,
        value: '20-30',
        },
      {
        no: 5,
        color: '#fbb938',
        idName: 40,
        value: '30-40',
        },
      {
        no: 6,
        color: '#e4440a',
        idName: 50,
        value: '40-50',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 50',
        },
    ],
    },
        {
        layer: ['Average tree height as of 2020, m', 'Average tree height as of 2050, m'],
    name: 'Average tree height, m',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 5,
        value: '<= 5',
      },
      {
        no: 2,
        color: '#34265c',
        idName: 10,
        value: '5-10',
        },
      {
        no: 3,
        color: '#36a7e3',
        idNname: 15,
        value: '10-15',
        },
      {
        no: 4,
        color: '#62f276',
        idName: 20,
        value: '15-20',
        },
      {
        no: 5,
        color: '#e1cd39',
        idName: 25,
        value: '20-25',
        },
      {
        no: 6,
        color: '#e7530f',
        idName: 30,
        value: '25-30',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 30',
        },
    ],
    },
     {
    layer: ['Stand basal area as of 2020, sq.m/ha', 'Stand basal area as of 2050, sq.m/ha'],
    name: 'Stand basal area, sq.m/ha',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 5,
        value: '<= 5',
      },
      {
        no: 2,
        color: '#4686fb',
        idName: 10,
        value: '5-10',
        },
      {
        no: 3,
        color: '#1ae5b6',
        idNname: 20,
        value: '10-20',
        },
      {
        no: 4,
        color: '#a4fc3c',
        idName: 30,
        value: '20-30',
        },
      {
        no: 5,
        color: '#fbb938',
        idName: 40,
        value: '30-40',
        },
      {
        no: 6,
        color: '#e4440a',
        idName: 50,
        value: '40-50',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 50',
        },
    ],
    },
    {
    layer: ['Growing stock as of 2020, cub.m/ha', 'Growing stock as of 2050, cub.m/ha'],
    name: 'Growing stock, cub.m/ha',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 50,
        value: '<= 50',
      },
      {
        no: 2,
        color: '#32b1dc',
        idName: 100,
        value: '50-100',
        },
      {
        no: 3,
        color: '#49ed8c',
        idNname: 250,
        value: '100-250',
        },
      {
        no: 4,
        color: '#a7fa3c',
        idName: 500,
        value: '250-500',
        },
      {
        no: 5,
        color: '#eb6617',
        idName: 600,
        value: '500-600',
        },
      {
        no: 6,
        color: '#b42706',
        idName: 700,
        value: '600-700',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 700',
        },
    ],
    },
    {
    layer: ['Trunk biomass as of 2020, t/ha', 'Trunk biomass as of 2050, t/ha',],
    name: 'Trunk biomass (wood+bark), t/ha',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 10,
        value: '<= 10',
      },
      {
        no: 2,
        color: '#4686fb',
        idName: 50,
        value: '10-50',
        },
      {
        no: 3,
        color: '#1ae5b6',
        idNname: 100,
        value: '50-100',
        },
      {
        no: 4,
        color: '#a4fc3c',
        idName: 150,
        value: '100-150',
        },
      {
        no: 5,
        color: '#fbb938',
        idName: 200,
        value: '150-200',
        },
      {
        no: 6,
        color: '#e4440a',
        idName: 250,
        value: '200-250',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 250',
        },
    ],
    },
        {
    layer: ['Above-ground biomass as of 2020, t/ha', 'Above-ground biomass as of 2050, t/ha',],
    name: 'Above-ground biomass of tree stand, t/ha',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 50,
        value: '<= 50',
      },
      {
        no: 2,
        color: '#4686fb',
        idName: 100,
        value: '50-100',
        },
      {
        no: 3,
        color: '#1ae5b6',
        idNname: 200,
        value: '100-200',
        },
      {
        no: 4,
        color: '#a4fc3c',
        idName: 250,
        value: '200-250',
        },
      {
        no: 5,
        color: '#fbb938',
        idName: 300,
        value: '250-300',
        },
      {
        no: 6,
        color: '#e4440a',
        idName: 350,
        value: '300-350',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 350',
        },
    ],
    },
    {
    layer: ['Sr-90 content in trunk wood as of 2020, Bq/kg', 'Cs-137 content in trunk wood as of 2020, Bq/kg'],
    name: 'Sr-90 / Cs-137 content in trunk wood as of 2020, Bq/kg',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 30,
        value: '<= 30',
      },
      {
        no: 2,
        color: '#466be3',
        idName: 60,
        value: '30-60',
        },
      {
        no: 3,
        color: '#28bceb',
        idNname: 120,
        value: '60-120',
        },
      {
        no: 4,
        color: '#32f298',
        idName: 600,
        value: '120-600',
        },
      {
        no: 5,
        color: '#a4fc3c',
        idName: 1200,
        value: '600-1200',
        },
      {
        no: 6,
        color: '#eecf3a',
        idName: 5000,
        value: '1200-5000',
        },
      {
        no: 7,
        color: '#fb7e21',
        idName: 10000,
        value: '5k-10k',
        },
      {
        no: 8,
        color: '#d02f05',
        idName: 100000,
        value: '10k-100k',
        },
      {
        no: 9,
        color: '#7a0403',
        idName: 'int',
        value: '> 100k',
        },
    ],
    },
        {
    layer: ['Probability of exceeding the permissible level of Sr-90 content in stem wood (60 Bq/kg) as of 2020, %', 'Probability of exceeding the permissible level of Cs-137 content in stem wood (600 Bq/kg) as of 2020, %'],
    name: 'Probability of exceeding the permissible level of Sr-90 and Cs-137 content in stem wood (60 and 600 Bq/kg, respectively) as of 2020, %',
    attributes: [
      {
        no: 1,
        color: '#041fa7',
        idName: 1,
        value: '<= 1',
      },
      {
        no: 2,
        color: '#1086fc',
        idName: 5,
        value: '1-5',
        },
      {
        no: 3,
        color: '#18d7cb',
        idNname: 10,
        value: '5-10',
        },
      {
        no: 4,
        color: '#47f882',
        idName: 25,
        value: '10-25',
        },
      {
        no: 5,
        color: '#a4fc3c',
        idName: 50,
        value: '25-50',
        },
      {
        no: 6,
        color: '#e3dc37',
        idName: 75,
        value: '50-75',
        },
      {
        no: 7,
        color: '#fea430',
        idName: 90,
        value: '75-90',
        },
      {
        no: 8,
        color: '#f05811',
        idName: 95,
        value: '90-95',
        },
      {
        no: 9,
        color: '#c22402',
        idName: 99,
        value: '95-99',
        },
      {
        no: 10,
        color: '#7a0403',
        idName: 'int',
        value: '> 99',
        },
    ],
    },
        {
    layer: ['External dose rate at a height of 1.0 m as of 2020, &mu;Gy/h', 'Internal dose rate as of 2020, &mu;Gy/h', 'Total dose rate as of 2020, &mu;Gy/h'],
    name: 'External / Internal / Total dose rate as of 2020, &mu;Gy/h',
    attributes: [
      {
        no: 1,
        color: '#30123b',
        idName: 0.15,
        value: '<= 0.15',
      },
      {
        no: 2,
        color: '#4686fb',
        idName: 0.3,
        value: '0.15-0.3',
        },
      {
        no: 3,
        color: '#1ae5b6',
        idNname: 0.6,
        value: '0.3-0.6',
        },
      {
        no: 4,
        color: '#a4fc3c',
        idName: 1.5,
        value: '0.6-1.5',
        },
      {
        no: 5,
        color: '#fbb938',
        idName: 3.0,
        value: '1.5-3.0',
        },
      {
        no: 6,
        color: '#e4440a',
        idName: 6.0,
        value: '3-6',
        },
      {
        no: 7,
        color: '#7a0403',
        idName: 'int',
        value: '> 6',
        },
    ],
  },
];
